version: 2
jobs:
  linter-check:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "package-lock.json" }}
      - run:
          name: install-eslint
          command: 'npx install-peerdeps --dev eslint-config-airbnb | sudo npm i -g eslint'
      - save_cache:
          key: v1-{{ checksum "package-lock.json" }}
          paths: "~/usr/local/lib/node_modules"
      - run:
          name: linter-check
          command: 'eslint ~/project/*.js'
workflows:
  version: 2
  check_and_test:
    jobs:
      - linter-check
