version: 2
jobs:
  linter-check:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "~/project/package.json" }}
      - run:
          name: install-airbnb
          command: cd ~/project && npm install
      - save_cache:
          key: v1-{{ checksum "~/project/package.json" }}
          paths: "~/project/node_modules"
      - run:
          name: linter-check
          command: '~/project/node_module/eslint/bin/eslint.js ~/project/'
workflows:
  version: 2
  check_and_test:
    jobs:
      - linter-check
