version: 2
jobs:
  linter-check:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "/usr/local/bin/eslint" }}
      - run:
          name: install-eslint
          command: 'sudo npm i -g eslint'
      - save_cache:
          key: v1-{{ checksum "/usr/local/bin/eslint" }}
          paths: "/usr/local/bin"
      - run:
          name: linter-check
          command: 'eslint ~/project/*.js'
workflows:
  version: 2
  check_and_test:
    jobs:
      - linter-check
