version: 2
jobs:
  one:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: install-eslint
          command: 'npm i -g eslint'
      - run:
          name: linter-check
          command: 'eslint ../test.js'
