version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: install-eslint
          command: 'sudo npm i -g eslint'
      - run:
          name: linter-check
          command: 'eslint ~/project/*.js'
workflows:
  version: 2
  check_and_test:
    jobs:
      - linter-check
